name: MLOps CI/CD Pipeline Training

on:
  push:
    branches:
      - training_pipelines

jobs:
  build_train_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_REGION: ${{ vars.GCP_REGION }}
      GCP_ARTIFACT_REGISTRY_REPO: ${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}
      GCP_VERTEX_BUCKET: ${{ vars.GCP_VERTEX_BUCKET }}
      GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}
      
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: "Configure Docker for Artifact Registry"
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: "Build and Push Trainer Docker Image"
        run: |
          IMAGE_TAG="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REGISTRY_REPO }}/house-price-trainer:latest"
          echo "Building Docker image: ${IMAGE_TAG}"
          docker build --platform linux/amd64 -t "${IMAGE_TAG}" .
          echo "Pushing Docker image: ${IMAGE_TAG}"
          docker push "${IMAGE_TAG}"

      - name: "Upload Data to GCS"
        run: |
          gsutil cp housing.csv gs://${{ env.GCP_VERTEX_BUCKET }}/data/housing.csv

      - name: "Execute Training Job on Vertex AI"
        id: custom_job_create
        run: |
          IMAGE_TAG="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REGISTRY_REPO }}/house-price-trainer:latest"
          JOB_DISPLAY_NAME="House-Price-Training-Job-$(date +%Y%m%d%H%M%S)"
          MODEL_OUTPUT_DIR="/gcs/${{ env.GCP_VERTEX_BUCKET }}/models/house-price-model"
          echo "Starting Vertex AI Custom Job: ${JOB_DISPLAY_NAME}"
          # Lanzar el job y capturar el resource name
          JOB_RESOURCE_NAME=$(gcloud ai custom-jobs create \
            --display-name="${JOB_DISPLAY_NAME}" \
            --region=${{ env.GCP_REGION }} \
            --worker-pool-spec=machine-type=n1-standard-4,replica-count=1,container-image-uri="${IMAGE_TAG}" \
            --args=--data-path=gs://${{ env.GCP_VERTEX_BUCKET }}/data/housing.csv,--model-dir="${MODEL_OUTPUT_DIR}" \
            --format="value(name)")
          echo "Custom Job resource name: ${JOB_RESOURCE_NAME}"
          if [ -z "$JOB_RESOURCE_NAME" ]; then
            echo "::error::Failed to create Vertex AI Custom Job."
            exit 1
          fi
          # Esperar a que el job termine
          echo "Waiting for Vertex AI Custom Job to complete..."
          while true; do
            JOB_STATE=$(gcloud ai custom-jobs describe "$JOB_RESOURCE_NAME" --region=${{ env.GCP_REGION }} --format="value(state)")
            echo "Current job state: $JOB_STATE"
            if [[ "$JOB_STATE" == "JOB_STATE_SUCCEEDED" ]]; then
              echo "Vertex AI Training job completed successfully."
              break
            elif [[ "$JOB_STATE" == "JOB_STATE_FAILED" || "$JOB_STATE" == "JOB_STATE_CANCELLED" ]]; then
              echo "::error::Vertex AI Training job failed or was cancelled."
              exit 1
            fi
            sleep 30
          done
